services:
  catalog1:
    build: ./src/catalog
    ports:
      - "4001:4000"
    environment:
      - REPLICA=catalog1
    volumes:
      - ./src/catalog/catalog.json:/app/catalog.json
    networks: 
      - proj-net

  catalog2:
    build: ./src/catalog
    ports:
      - "4002:4000"
    environment:
      - REPLICA=catalog2
    volumes:
      - ./src/catalog/catalog.json:/app/catalog.json
    networks: 
      - proj-net

  order1:
    build: ./src/order
    ports:
      - "3001:3000"
    environment:
      - REPLICA=order1
    volumes:
      - ./src/order/orders.json:/app/orders.json
    networks: 
      - proj-net

  order2:
    build: ./src/order
    ports:
      - "3002:3000"
    environment:
      - REPLICA=order2
    volumes:
      - ./src/order/orders.json:/app/orders.json
    networks: 
      - proj-net

  frontend:
    build: ./src/front-end
    ports:
      - "5000:5000"
    networks:
      - proj-net
    depends_on:
      - catalog1
      - catalog2
      - order1
      - order2

networks:
  proj-net:
    driver: bridge